force-app/main/default/objects/ozbee__Production_Schedule_Item__c/ozbee__Production_Schedule_Item__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >ozbee__Production_Schedule_Layout</compactLayoutAssignment>
    <label>Production Schedule Item</label>
    <nameField>
        <label>Task / Phase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Schedule Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ozbee__Production_Schedule_Item__c/fields/SOW_Item__c.field-meta.xml
<CustomField>
    <fullName>SOW_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SOW Item</label>
    <referenceTo>SOW_Item__c</referenceTo>
    <relationshipLabel>Production Schedule Items</relationshipLabel>
    <relationshipName>Production_Schedule_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SOW_Item__c/SOW_Item__c.object-meta.xml
<CustomObject>
    <label>SOW Item</label>
    <nameField>
        <displayFormat>SOWI-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOW Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SOW_Item__c/fields/Production_Schedule_Item__c.field-meta.xml
<CustomField>
    <fullName>Production_Schedule_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Production Schedule Item</label>
    <referenceTo>ozbee__Production_Schedule_Item__c</referenceTo>
    <relationshipLabel>SOW Items</relationshipLabel>
    <relationshipName>SOW_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SOWItemService.cls
public with sharing class SOWItemService {
  public static void deleteParentProductionScheduleItems(
    List<SOW_Item__c> oldSOWItems
  ) {
    Set<Id> productionScheduleIds = Pluck.ids(
      'Production_Schedule_Item__c',
      oldSOWItems
    );

    List<ozbee__Production_Schedule_Item__c> parentProductionScheduleItems = [
      SELECT Id
      FROM ozbee__Production_Schedule_Item__c
      WHERE Id IN :productionScheduleIds
    ];

    if (!parentProductionScheduleItems.isEmpty()) {
      delete parentProductionScheduleItems;
    }
  }
}