force-app/main/default/objects/ozbee__Production_Job__c/ozbee__Production_Job__c.object-meta.xml
<CustomObject>
    <label>Production Job</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Production Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Production Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ozbee__Production_Schedule_Item__c/ozbee__Production_Schedule_Item__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >ozbee__Production_Schedule_Layout</compactLayoutAssignment>
    <label>Production Schedule Item</label>
    <nameField>
        <label>Task / Phase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Schedule Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ozbee__Production_Schedule_Item__c/fields/SOW_Item__c.field-meta.xml
<CustomField>
    <fullName>SOW_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SOW Item</label>
    <referenceTo>SOW_Item__c</referenceTo>
    <relationshipLabel>Production Schedule Items</relationshipLabel>
    <relationshipName>Production_Schedule_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SOW__c/SOW__c.object-meta.xml
<CustomObject>
    <label>SOW</label>
    <nameField>
        <label>SOW Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SOWs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SOW__c/fields/Production_Job__c.field-meta.xml
<CustomField>
    <fullName>Production_Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Production Job</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>ozbee__Production_Job__c.ozbee__Opportunity__c</field>
            <operation>equals</operation>
            <valueField>$Source.Opportunity__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ozbee__Production_Job__c</referenceTo>
    <relationshipName>SoWs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SOW__c/fields/Ready_to_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Ready_to_Schedule__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ready to Schedule</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SOW_Item__c/SOW_Item__c.object-meta.xml
<CustomObject>
    <label>SOW Item</label>
    <nameField>
        <displayFormat>SOWI-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOW Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SOW_Item__c/fields/Production_Schedule_Item__c.field-meta.xml
<CustomField>
    <fullName>Production_Schedule_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Production Schedule Item</label>
    <referenceTo>ozbee__Production_Schedule_Item__c</referenceTo>
    <relationshipLabel>SOW Items</relationshipLabel>
    <relationshipName>SOW_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SOW_Item__c/fields/Schedule_Generated__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Generated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Schedule Generated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SOW_Item__c/fields/SOW__c.field-meta.xml
<CustomField>
    <fullName>SOW__c</fullName>
    <label>SOW</label>
    <referenceTo>SOW__c</referenceTo>
    <relationshipLabel>SOW Items</relationshipLabel>
    <relationshipName>SOW_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SOW_Item__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/GenerateProductionScheduleControllerTest.cls
@isTest
public with sharing class GenerateProductionScheduleControllerTest {
  @IsTest
  private static void createProductionScheduleItems_exception() {
    ozbee__Production_Job__c productionJob = (ozbee__Production_Job__c) new SObjectBuilder(
        ozbee__Production_Job__c.sObjectType
      )
      .create()
      .getRecord();

    Boolean error = false;

    Test.startTest();
    try {
      GenerateProductionScheduleController.createProductionScheduleItems(
        productionJob.Id
      );
    } catch (Exception e) {
      error = true;
    }
    Test.stopTest();

    System.assertEquals(true, error, 'Exception was not thrown');
  }

  @IsTest
  private static void createProductionScheduleItems_success() {
    ozbee__Production_Job__c productionJob = (ozbee__Production_Job__c) new SObjectBuilder(
        ozbee__Production_Job__c.sObjectType
      )
      .create()
      .getRecord();

    SOW__c sow = (SOW__c) new SObjectBuilder(SOW__c.sObjectType)
      .put(SOW__c.Production_Job__c, productionJob.Id)
      .put(SOW__c.Ready_to_Schedule__c, true)
      .create()
      .getRecord();

    List<SOW_Item__c> sowItems = new SObjectBuilder(SOW_Item__c.sObjectType)
      .put(SOW_Item__c.SOW__c, sow.Id)
      .put(SOW_Item__c.Start_Date__c, Date.Today() + 1)
      .put(SOW_Item__c.End_Date__c, Date.Today() + 2)
      .create()
      .getRecords();

    Test.startTest();
    GenerateProductionScheduleController.createProductionScheduleItems(
      productionJob.Id
    );
    Test.stopTest();

    List<ozbee__Production_Schedule_Item__c> items = [
      SELECT Id
      FROM ozbee__Production_Schedule_Item__c
    ];

    System.AssertEquals(1, items.size(), 'No production schedule items');

    List<SOW_Item__c> updatedSOWItems = [
      SELECT Id, Schedule_Generated__c, Production_Schedule_Item__c
      FROM SOW_Item__c
    ];

    System.AssertEquals(
      1,
      updatedSOWItems.size(),
      'The updated SOW items list size is not equal to 1'
    );
    System.AssertEquals(
      true,
      updatedSOWItems[0].Schedule_Generated__c,
      'Schedule generated was not correctly set'
    );
    System.AssertEquals(
      items[0].Id,
      updatedSOWItems[0].Production_Schedule_Item__c,
      'The Production schedule item lookup was not correctly set'
    );
  }
}