force-app/main/default/objects/ozbee__Production_Job__c/ozbee__Production_Job__c.object-meta.xml
<CustomObject>
    <label>Production Job</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Production Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Production Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SOW__c/SOW__c.object-meta.xml
<CustomObject>
    <label>SOW</label>
    <nameField>
        <label>SOW Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SOWs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SOW__c/fields/Production_Job__c.field-meta.xml
<CustomField>
    <fullName>Production_Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Production Job</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>ozbee__Production_Job__c.ozbee__Opportunity__c</field>
            <operation>equals</operation>
            <valueField>$Source.Opportunity__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ozbee__Production_Job__c</referenceTo>
    <relationshipName>SoWs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProductionJobServiceTest.cls
@isTest
public with sharing class ProductionJobServiceTest {
  @isTest
  private static void setSOWProductionJob() {
    List<ozbee__Production_Job__c> productionJobs = (List<ozbee__Production_Job__c>) new SObjectBuilder(
        ozbee__Production_Job__c.sObjectType
      )
      .create()
      .getRecords();

    List<SOW__c> sows = (List<SOW__c>) new SObjectBuilder(SOW__c.sObjectType)
      .create()
      .getRecords();

    Test.startTest();
    ProductionJobService.setSOWProductionJob(productionJobs);
    Test.stopTest();

    List<SOW__c> updatedSows = [SELECT Production_Job__c FROM SOW__c];

    System.assertEquals(
      productionJobs[0].Id,
      updatedSows[0].Production_Job__c,
      'Production job Ids are not equal'
    );
  }
}