force-app/main/default/objects/ozbee__Production_Job__c/ozbee__Production_Job__c.object-meta.xml
<CustomObject>
    <label>Production Job</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Production Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Production Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SOW__c/SOW__c.object-meta.xml
<CustomObject>
    <label>SOW</label>
    <nameField>
        <label>SOW Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SOWs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SOW__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>SOWs</relationshipLabel>
    <relationshipName>SOWs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SOW__c/fields/Production_Job__c.field-meta.xml
<CustomField>
    <fullName>Production_Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Production Job</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>ozbee__Production_Job__c.ozbee__Opportunity__c</field>
            <operation>equals</operation>
            <valueField>$Source.Opportunity__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ozbee__Production_Job__c</referenceTo>
    <relationshipName>SoWs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SOW__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Template 1</fullName>
            </value>
            <value>
                <fullName>Template 2</fullName>
            </value>
            <value>
                <fullName>Template 3</fullName>
            </value>
            <value>
                <fullName>Captiva Test SOW Template</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SOW_Item__c/SOW_Item__c.object-meta.xml
<CustomObject>
    <label>SOW Item</label>
    <nameField>
        <displayFormat>SOWI-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOW Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SOW_Item__c/fields/SOW__c.field-meta.xml
<CustomField>
    <fullName>SOW__c</fullName>
    <label>SOW</label>
    <referenceTo>SOW__c</referenceTo>
    <relationshipLabel>SOW Items</relationshipLabel>
    <relationshipName>SOW_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SOW_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SOW_Item_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SOW_Item__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SOW_Item_Template__c/SOW_Item_Template__c.object-meta.xml
<CustomObject>
    <label>SOW Item Template</label>
    <nameField>
        <displayFormat>SOWT-{0000}</displayFormat>
        <label>SOW Item Template</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOW Item Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SOW_Item_Template__c/fields/SOW_Template__c.field-meta.xml
<CustomField>
    <fullName>SOW_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SOW Template</label>
    <referenceTo>SOW_Template__c</referenceTo>
    <relationshipLabel>SOW Item Templates</relationshipLabel>
    <relationshipName>SOW_Item_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SOW_Item_Template__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SOW_Template__c/SOW_Template__c.object-meta.xml
<CustomObject>
    <label>SOW Template</label>
    <nameField>
        <label>SOW Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SOW Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/SOW_Item_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
        <default>true</default>
        <label>Not Started</label>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <masterLabel>SOW Item Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SOWService.cls
public with sharing class SOWService {
  public static void setProductionJob(List<SOW__c> SOWs) {
    Map<Id, Opportunity> opportunities = new Map<Id, Opportunity>(
      [
        SELECT Id, (SELECT Id FROM ozbee__Production_Centers__r)
        FROM Opportunity
        WHERE Id IN :Pluck.ids('Opportunity__c', SOWs)
      ]
    );

    for (SOW__c SOW : SOWs) {
      List<ozbee__Production_Job__c> productionJobs = opportunities.get(
          SOW.Opportunity__c
        )
        .ozbee__Production_Centers__r;
      if (productionJobs.size() > 0) {
        SOW.Production_Job__c = productionJobs[0].Id;
      }
    }
  }

  public static void createSOWItemsFromTemplate(List<SOW__c> SOWs) {
    List<SOW__c> filteredSOWs = new List<SOW__c>();

    for (SOW__C SOW : SOWs) {
      if (SOW.Type__c != null) {
        filteredSOWs.add(SOW);
      }
    }

    if (filteredSOWs.size() == 0) {
      return;
    }

    List<SOW_Template__c> SOWTemplates = [
      SELECT
        Id,
        Name,
        (SELECT Id, Title__c, Description__c FROM SOW_Item_Templates__r)
      FROM SOW_Template__c
      WHERE Name IN :Pluck.strings('Type__c', filteredSOWs)
    ];

    Map<String, SOW_Template__c> SOWTemplateMap = new Map<String, SOW_Template__c>();

    for (SOW_Template__c SOWTemplate : SOWTemplates) {
      SOWTemplateMap.put(SOWTemplate.Name, SOWTemplate);
    }

    List<SOW_Item__c> SOWItemsToInsert = new List<SOW_Item__c>();

    for (SOW__c SOW : filteredSOWs) {
      for (
        SOW_Item_Template__c SOWItemTemplate : SOWTemplateMap.get(SOW.Type__c)
          .SOW_Item_Templates__r
      ) {
        SOWItemsToInsert.add(
          new SOW_Item__c(
            SOW__c = SOW.Id,
            Title__c = SOWItemTemplate.Title__c,
            Description__c = SOWItemTemplate.Description__c,
            Status__c = 'Not Started'
          )
        );
      }
    }

    if (SOWItemsToInsert.size() > 0) {
      insert SOWItemsToInsert;
    }
  }
}