force-app/main/default/objects/ozbee__Production_Job__c/ozbee__Production_Job__c.object-meta.xml
<CustomObject>
    <label>Production Job</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Production Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Production Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SOW__c/SOW__c.object-meta.xml
<CustomObject>
    <label>SOW</label>
    <nameField>
        <label>SOW Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SOWs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SOW__c/fields/Production_Job__c.field-meta.xml
<CustomField>
    <fullName>Production_Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Production Job</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>ozbee__Production_Job__c.ozbee__Opportunity__c</field>
            <operation>equals</operation>
            <valueField>$Source.Opportunity__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ozbee__Production_Job__c</referenceTo>
    <relationshipName>SoWs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SOW__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Template 1</fullName>
            </value>
            <value>
                <fullName>Template 2</fullName>
            </value>
            <value>
                <fullName>Template 3</fullName>
            </value>
            <value>
                <fullName>Captiva Test SOW Template</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SOW_Item__c/SOW_Item__c.object-meta.xml
<CustomObject>
    <label>SOW Item</label>
    <nameField>
        <displayFormat>SOWI-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOW Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SOW_Item__c/fields/Previous_Item__c.field-meta.xml
<CustomField>
    <fullName>Previous_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Previous Item</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Previous item must belong to the same SOW</errorMessage>
        <filterItems>
            <field>SOW_Item__c.SOW__c</field>
            <operation>equals</operation>
            <valueField>$Source.SOW__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SOW_Item__c</referenceTo>
    <relationshipLabel>SOW Items</relationshipLabel>
    <relationshipName>SOW_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SOW_Item__c/fields/SOW__c.field-meta.xml
<CustomField>
    <fullName>SOW__c</fullName>
    <label>SOW</label>
    <referenceTo>SOW__c</referenceTo>
    <relationshipLabel>SOW Items</relationshipLabel>
    <relationshipName>SOW_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SOW_Item_Template__c/SOW_Item_Template__c.object-meta.xml
<CustomObject>
    <label>SOW Item Template</label>
    <nameField>
        <displayFormat>SOWT-{0000}</displayFormat>
        <label>SOW Item Template</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOW Item Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SOW_Item_Template__c/fields/SOW_Template__c.field-meta.xml
<CustomField>
    <fullName>SOW_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SOW Template</label>
    <referenceTo>SOW_Template__c</referenceTo>
    <relationshipLabel>SOW Item Templates</relationshipLabel>
    <relationshipName>SOW_Item_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SOW_Template__c/SOW_Template__c.object-meta.xml
<CustomObject>
    <label>SOW Template</label>
    <nameField>
        <label>SOW Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SOW Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SOWServiceTest.cls
@isTest
public class SOWServiceTest {
  @isTest
  private static void setProductionJob() {
    List<SOW__c> sowList = new SObjectBuilder(SOW__c.sObjectType)
      .count(1)
      .create()
      .getRecords();

    ozbee__Production_Job__c productionJob = (ozbee__Production_Job__c) new SObjectBuilder(
        ozbee__Production_Job__c.sObjectType
      )
      .create()
      .getRecord();

    Test.startTest();
    SOWService.setProductionJob(sowList);
    Test.stopTest();

    List<SOW__c> updateSOWs = [SELECT Id, Production_Job__c FROM SOW__c];

    Assert.areEqual(
      1,
      updateSOWs.size(),
      'Exactly 1 SOW record was not retuend'
    );
    Assert.areEqual(
      productionJob.Id,
      updateSOWs[0].Production_Job__c,
      'Incorrect production job was assigned'
    );
  }

  @isTest
  private static void createSOWItemsFromTemplate_WithTemplate() {
    List<SOW_Item_Template__c> sowItemTemplates = new SObjectBuilder(
        SOW_Item_Template__c.sObjectType
      )
      .put(
        SOW_Item_Template__c.SOW_Template__c,
        SObjectFactory.provideGenericParent(
          SOW_Template__c.sObjectType,
          SOW_Template__c.Name,
          'Template 1'
        )
      )
      .count(5)
      .create()
      .getRecords();

    Test.startTest();
    List<SOW__c> sowList = new SObjectBuilder(SOW__c.sObjectType)
      .put(SOW__c.Type__c, 'Template 1')
      .count(1)
      .create()
      .getRecords();
    Test.stopTest();

    List<SOW__c> updatedSOWs = [
      SELECT Id, (SELECT Id FROM SOW_Items__r)
      FROM SOW__c
    ];

    Assert.areEqual(1, updatedSOWs.size(), 'Not exactly 1 SOW was created');
    Assert.areEqual(
      5,
      updatedSOWs[0].SOW_Items__r.size(),
      'Not exactly 5 SOW Items were created'
    );
  }

  @isTest
  private static void createSOWItemsFromTemplate_WithoutTemplate() {
    Test.startTest();
    List<SOW__c> sowList = new SObjectBuilder(SOW__c.sObjectType)
      .count(1)
      .create()
      .getRecords();
    Test.stopTest();

    List<SOW__c> updatedSOWs = [
      SELECT Id, (SELECT Id FROM SOW_Items__r)
      FROM SOW__c
    ];

    Assert.areEqual(1, updatedSOWs.size(), 'Not exactly 1 SOW was created');
    Assert.areEqual(
      0,
      updatedSOWs[0].SOW_Items__r.size(),
      '0 SOW Items should have been created'
    );
  }
}