force-app/main/default/objects/ozbee__Production_Job__c/ozbee__Production_Job__c.object-meta.xml
<CustomObject>
    <label>Production Job</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Production Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Production Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ozbee__Production_Schedule_Item__c/ozbee__Production_Schedule_Item__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >ozbee__Production_Schedule_Layout</compactLayoutAssignment>
    <label>Production Schedule Item</label>
    <nameField>
        <label>Task / Phase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Schedule Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ozbee__Production_Schedule_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Budgeted Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ozbee__Production_Schedule_Item__c/fields/SOW_Item__c.field-meta.xml
<CustomField>
    <fullName>SOW_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SOW Item</label>
    <referenceTo>SOW_Item__c</referenceTo>
    <relationshipLabel>Production Schedule Items</relationshipLabel>
    <relationshipName>Production_Schedule_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SOW__c/SOW__c.object-meta.xml
<CustomObject>
    <label>SOW</label>
    <nameField>
        <label>SOW Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SOWs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SOW__c/fields/Production_Job__c.field-meta.xml
<CustomField>
    <fullName>Production_Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Production Job</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>ozbee__Production_Job__c.ozbee__Opportunity__c</field>
            <operation>equals</operation>
            <valueField>$Source.Opportunity__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ozbee__Production_Job__c</referenceTo>
    <relationshipName>SoWs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SOW__c/fields/Ready_to_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Ready_to_Schedule__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ready to Schedule</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SOW_Item__c/SOW_Item__c.object-meta.xml
<CustomObject>
    <label>SOW Item</label>
    <nameField>
        <displayFormat>SOWI-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOW Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SOW_Item__c/fields/Measurement__c.field-meta.xml
<CustomField>
    <fullName>Measurement__c</fullName>
    <label>Measurement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Squares</fullName>
            </value>
            <value>
                <fullName>Linear FT</fullName>
            </value>
            <value>
                <fullName>Each</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SOW_Item__c/fields/Previous_Item__c.field-meta.xml
<CustomField>
    <fullName>Previous_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Previous Item</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Previous item must belong to the same SOW</errorMessage>
        <filterItems>
            <field>SOW_Item__c.SOW__c</field>
            <operation>equals</operation>
            <valueField>$Source.SOW__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SOW_Item__c</referenceTo>
    <relationshipLabel>SOW Items</relationshipLabel>
    <relationshipName>SOW_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SOW_Item__c/fields/Production_Schedule_Item__c.field-meta.xml
<CustomField>
    <fullName>Production_Schedule_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Production Schedule Item</label>
    <referenceTo>ozbee__Production_Schedule_Item__c</referenceTo>
    <relationshipLabel>SOW Items</relationshipLabel>
    <relationshipName>SOW_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SOW_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SOW_Item__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <label>Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SOW_Item__c/fields/Schedule_Generated__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Generated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Schedule Generated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SOW_Item__c/fields/SOW__c.field-meta.xml
<CustomField>
    <fullName>SOW__c</fullName>
    <label>SOW</label>
    <referenceTo>SOW__c</referenceTo>
    <relationshipLabel>SOW Items</relationshipLabel>
    <relationshipName>SOW_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SOW_Item__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SOW_Item__c/fields/Task_Phase__c.field-meta.xml
<CustomField>
    <fullName>Task_Phase__c</fullName>
    <label>Task / Phase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single Ply</fullName>
            </value>
            <value>
                <fullName>Labor</fullName>
            </value>
            <value>
                <fullName>Built Up</fullName>
            </value>
            <value>
                <fullName>Tile</fullName>
            </value>
            <value>
                <fullName>Shingle</fullName>
            </value>
            <value>
                <fullName>Standing Seam</fullName>
            </value>
            <value>
                <fullName>Material Delivery</fullName>
            </value>
            <value>
                <fullName>Shutdown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SOW_Item__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/GenerateProductionScheduleController.cls
public with sharing class GenerateProductionScheduleController {
  @AuraEnabled
  public static void createProductionScheduleItems(Id productionJobId) {
    try {
      List<SOW__c> SOWs = [
        SELECT
          Id,
          (
            SELECT
              Id,
              Name,
              Title__c,
              Description__c,
              Quantity__c,
              Measurement__c,
              Start_Date__c,
              End_Date__c,
              Task_Phase__c,
              Revenue__c
            FROM SOW_Items__r
            WHERE Schedule_Generated__c = FALSE
          )
        FROM SOW__c
        WHERE
          Production_Job__c = :productionJobId
          AND Ready_to_Schedule__c = TRUE
      ];

      if (SOWs.size() == 0) {
        throw new thrownException('This production job does not have a SOW');
      }

      List<ozbee__Production_Schedule_Item__c> productionScheduleItemsToInsert = new List<ozbee__Production_Schedule_Item__c>();
      List<SOW_Item__c> sowItemsToUpdate = new List<SOW_Item__c>();

      Map<Id, SOW_Item__c> sowItemIdToSOWItem = new Map<Id, SOW_Item__c>();
      for (SOW__c SOW : SOWs) {
        for (SOW_Item__c SOWItem : SOW.SOW_Items__r) {
          if (SOWItem.Start_Date__c == null || SOWItem.End_Date__c == null) {
            continue;
          }

          Integer startDay = SOWItem.Start_Date__c.day();
          Integer startMonth = SOWItem.Start_Date__c.month();
          Integer startYear = SOWItem.Start_Date__c.year();

          Integer endDay = SOWItem.End_Date__c.day();
          Integer endMonth = SOWItem.End_Date__c.month();
          Integer endYear = SOWItem.End_Date__c.year();

          productionScheduleItemsToInsert.add(
            new ozbee__Production_Schedule_Item__c(
              ozbee__Production_Job__c = productionJobId,
              Name = SOWItem.Title__c,
              ozbee__Start_Date__c = Datetime.newInstance(
                startYear,
                startMonth,
                startDay,
                7,
                0,
                0
              ),
              ozbee__End_Date__c = Datetime.newInstance(
                endYear,
                endMonth,
                endDay,
                17,
                0,
                0
              ),
              ozbee__Type__c = SOWItem.Task_Phase__c,
              ozbee__Total_Days__c = SOWItem.Start_Date__c.daysBetween(
                  SOWItem.End_Date__c
                ) + 1,
              Quantity__c = SOWItem.Quantity__c,
              Measurement__c = SOWItem.Measurement__c,
              ozbee__Total_Revenue__c = SOWItem.Revenue__c,
              SOW_Item__c = SOWItem.Id
            )
          );
          sowItemIdToSOWItem.put(SOWItem.Id, SOWItem);
          sowItemsToUpdate.add(SOWItem);
        }
      }
      if (productionScheduleItemsToInsert.size() == 0) {
        throw new thrownException('No valid SOW Items');
      } else {
        insert productionScheduleItemsToInsert;

        for (
          ozbee__Production_Schedule_Item__c productionScheduleItem : productionScheduleItemsToInsert
        ) {
          sowItemIdToSOWItem.get(productionScheduleItem.SOW_Item__c)
            .Schedule_Generated__c = true;
          sowItemIdToSOWItem.get(productionScheduleItem.SOW_Item__c)
            .Production_Schedule_Item__c = productionScheduleItem.Id;
        }
        update sowItemsToUpdate;
      }
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  public class thrownException extends Exception {
  }
}