force-app/main/default/objects/ozbee__Production_Job__c/ozbee__Production_Job__c.object-meta.xml
<CustomObject>
    <label>Production Job</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Production Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Production Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ozbee__Production_Job__c/fields/Percent_Complete__c.field-meta.xml
<CustomField>
    <fullName>Percent_Complete__c</fullName>
    <label>Total Squares Complete %</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ozbee__Production_Schedule_Item__c/ozbee__Production_Schedule_Item__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >ozbee__Production_Schedule_Layout</compactLayoutAssignment>
    <label>Production Schedule Item</label>
    <nameField>
        <label>Task / Phase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Schedule Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ozbee__Production_Schedule_Item__c/fields/Completed__c.field-meta.xml
<CustomField>
    <fullName>Completed__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Completed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ozbee__Production_Schedule_Item__c/fields/Percent_Complete__c.field-meta.xml
<CustomField>
    <fullName>Percent_Complete__c</fullName>
    <formula>Completed__c / Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Percent Complete</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ozbee__Production_Schedule_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Budgeted Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SOW__c/SOW__c.object-meta.xml
<CustomObject>
    <label>SOW</label>
    <nameField>
        <label>SOW Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SOWs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SOW__c/fields/Percent_Complete__c.field-meta.xml
<CustomField>
    <fullName>Percent_Complete__c</fullName>
    <formula>IF(
   Total_Items__c = 0,
   0,
   Completed_Items__c /  Total_Items__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Percent Complete</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SOW__c/fields/Production_Job__c.field-meta.xml
<CustomField>
    <fullName>Production_Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Production Job</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>ozbee__Production_Job__c.ozbee__Opportunity__c</field>
            <operation>equals</operation>
            <valueField>$Source.Opportunity__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ozbee__Production_Job__c</referenceTo>
    <relationshipName>SoWs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProductionJobService.cls
public with sharing class ProductionJobService {
  public static void setSOWProductionJob(
    List<ozbee__Production_Job__c> productionJobs
  ) {
    Map<Id, Opportunity> opportunities = new Map<Id, Opportunity>(
      [
        SELECT Id, (SELECT Id, Production_Job__c FROM SOWs__r)
        FROM Opportunity
        WHERE Id IN :Pluck.ids('ozbee__Opportunity__c', productionJobs)
      ]
    );

    List<SOW__c> SOWToUpdate = new List<SOW__c>();

    for (ozbee__Production_Job__c productionJob : productionJobs) {
      List<SOW__c> SOWs = opportunities.get(productionJob.ozbee__Opportunity__c)
        .SOWs__r;
      for (SOW__c SOW : SOWs) {
        SOW.Production_Job__c = productionJob.Id;
        SOWToUpdate.add(SOW);
      }
    }

    update SOWToUpdate;
  }

  public static void calculatePercentComplete(Set<Id> productionJobIds) {
    List<ozbee__Production_Job__c> productionJobs = [
      SELECT
        Id,
        Percent_Complete__c,
        (
          SELECT Id, Quantity__c, Completed__c, Measurement__c
          FROM ozbee__Production_Schedule_Items__r
        )
      FROM ozbee__Production_Job__c
      WHERE Id IN :productionJobIds
    ];

    for (ozbee__Production_Job__c productionJob : productionJobs) {
      Decimal total = 0;
      Decimal completed = 0;

      for (
        ozbee__Production_Schedule_Item__c productionScheduleItem : productionJob.ozbee__Production_Schedule_Items__r
      ) {
        if (productionScheduleItem.Measurement__c == 'Squares') {
          total += productionScheduleItem.Quantity__c;
          completed += productionScheduleItem.Completed__c;
        }
      }

      productionJob.Percent_Complete__c = completed / total * 100;
    }

    update productionJobs;
  }
}