force-app/main/default/objects/Daily_Expected_Production__c/Daily_Expected_Production__c.object-meta.xml
<CustomObject>
    <label>Daily Expected Production</label>
    <nameField>
        <displayFormat>DEP-{0000}</displayFormat>
        <label>Daily Expected Production Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Expected Productions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Expected_Production__c/fields/Completed__c.field-meta.xml
<CustomField>
    <fullName>Completed__c</fullName>
    <label>Completed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Daily_Expected_Production__c/fields/Completed_Today__c.field-meta.xml
<CustomField>
    <fullName>Completed_Today__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Completed Today</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Daily_Expected_Production__c/fields/Daily_Report__c.field-meta.xml
<CustomField>
    <fullName>Daily_Report__c</fullName>
    <label>Daily Report</label>
    <referenceTo>ozbee__Production_Job_Report__c</referenceTo>
    <relationshipLabel>Daily Expected Productions</relationshipLabel>
    <relationshipName>Daily_Expected_Productions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Daily_Expected_Production__c/fields/Expected__c.field-meta.xml
<CustomField>
    <fullName>Expected__c</fullName>
    <label>Expected</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Daily_Expected_Production__c/fields/Expected_Total__c.field-meta.xml
<CustomField>
    <fullName>Expected_Total__c</fullName>
    <label>Expected Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Daily_Expected_Production__c/fields/Measurement__c.field-meta.xml
<CustomField>
    <fullName>Measurement__c</fullName>
    <label>Measurement</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Expected_Production__c/fields/Previously_Completed__c.field-meta.xml
<CustomField>
    <fullName>Previously_Completed__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Previously Completed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Daily_Expected_Production__c/fields/Production_Schedule_Item__c.field-meta.xml
<CustomField>
    <fullName>Production_Schedule_Item__c</fullName>
    <label>Production Schedule Item</label>
    <referenceTo>ozbee__Production_Schedule_Item__c</referenceTo>
    <relationshipLabel>Daily Expected Productions</relationshipLabel>
    <relationshipName>Daily_Expected_Productions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ozbee__Production_Schedule_Item__c/ozbee__Production_Schedule_Item__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >ozbee__Production_Schedule_Layout</compactLayoutAssignment>
    <label>Production Schedule Item</label>
    <nameField>
        <label>Task / Phase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Schedule Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ozbee__Production_Schedule_Item__c/fields/Completed__c.field-meta.xml
<CustomField>
    <fullName>Completed__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Completed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DailyExpectedProductionService.cls
public with sharing class DailyExpectedProductionService {
  @AuraEnabled
  public static List<Daily_Expected_Production__c> getDailyReportExpectedProduction(
    Id dailyReportId
  ) {
    return [
      SELECT
        Id,
        Name,
        Expected_Total__c,
        Previously_Completed__c,
        Completed_Today__c,
        Expected__c,
        Completed__c,
        Measurement__c,
        Production_Schedule_Item__r.Name
      FROM Daily_Expected_Production__c
      WHERE Daily_Report__c = :dailyReportId
    ];
  }
}