force-app/main/default/objects/Daily_Expected_Production__c/Daily_Expected_Production__c.object-meta.xml
<CustomObject>
    <label>Daily Expected Production</label>
    <nameField>
        <displayFormat>DEP-{0000}</displayFormat>
        <label>Daily Expected Production Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Expected Productions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Report_Checklist__c/Daily_Report_Checklist__c.object-meta.xml
<CustomObject>
    <label>Daily Report Checklist</label>
    <nameField>
        <displayFormat>DRC-{000000000}</displayFormat>
        <label>Daily Report Checklists</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Report Checklists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ozbee__Production_Job__c/ozbee__Production_Job__c.object-meta.xml
<CustomObject>
    <label>Production Job</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Production Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Production Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ozbee__Production_Job_Checklist_Template__c/ozbee__Production_Job_Checklist_Template__c.object-meta.xml
<CustomObject>
    <label>Production Job Checklist Template</label>
    <nameField>
        <displayFormat>PJCT-{000000000}</displayFormat>
        <label>Production Job Checklist Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Production Job Checklist Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ozbee__Production_Job_Checklist_Template_Item__c/ozbee__Production_Job_Checklist_Template_Item__c.object-meta.xml
<CustomObject>
    <label>Production Job Checklist Template Item</label>
    <nameField>
        <displayFormat>PJCTI-{000000000}</displayFormat>
        <label>Production Job Checklist Template Items</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Production Job Checklist Template Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ozbee__Production_Job_Checklist_Template_Item__c/fields/ozbee__Production_Job_Checklist_Template__c.field-meta.xml
<CustomField>
    <fullName>ozbee__Production_Job_Checklist_Template__c</fullName>
    <label>Production Job Checklist Template</label>
    <referenceTo>ozbee__Production_Job_Checklist_Template__c</referenceTo>
    <relationshipLabel
  >Production Job Checklist Template Items</relationshipLabel>
    <relationshipName>Production_Job_Checklist_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ozbee__Production_Job_Report__c/ozbee__Production_Job_Report__c.object-meta.xml
<CustomObject>
    <label>Daily Report</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{DD}-{000000000}</displayFormat>
        <label>Daily Report Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ozbee__Production_Job_Report__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Daily Reports</relationshipLabel>
    <relationshipName>Daily_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ozbee__Production_Job_Report_Item__c/ozbee__Production_Job_Report_Item__c.object-meta.xml
<CustomObject>
    <label>Daily Report Item</label>
    <nameField>
        <label>Daily Report Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Daily Report Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ozbee__Production_Job_Report_Photo__c/ozbee__Production_Job_Report_Photo__c.object-meta.xml
<CustomObject>
    <label>Daily Report Photo</label>
    <nameField>
        <displayFormat>DRP-{000000000}</displayFormat>
        <label>Daily Report Photo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Report Photos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ozbee__Production_Schedule_Item__c/ozbee__Production_Schedule_Item__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >ozbee__Production_Schedule_Layout</compactLayoutAssignment>
    <label>Production Schedule Item</label>
    <nameField>
        <label>Task / Phase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Schedule Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DailyReportServiceTest.cls
@isTest
private class DailyReportServiceTest {
  @TestSetup
  static void setup() {
    Opportunity opportunity = (Opportunity) new SObjectBuilder(
        Opportunity.sObjectType
      )
      .put(Opportunity.CloseDate, Date.today() - 7)
      .create()
      .getRecord();

    ozbee__Production_Job__c productionJob = (ozbee__Production_Job__c) new SObjectBuilder(
        ozbee__Production_Job__c.sObjectType
      )
      .put(ozbee__Production_Job__c.ozbee__Opportunity__c, opportunity.Id)
      .create()
      .getRecord();

    ozbee__Production_Job_Report__c dailyReport = (ozbee__Production_Job_Report__c) new SObjectBuilder(
        ozbee__Production_Job_Report__c.sObjectType
      )
      .put(
        ozbee__Production_Job_Report__c.ozbee__Production_Job__c,
        productionJob.Id
      )
      .put(ozbee__Production_Job_Report__c.Opportunity__c, opportunity.Id)
      .create()
      .getRecord();

    new SObjectBuilder(ozbee__Production_Job_Report_Photo__c.sObjectType)
      .put(
        ozbee__Production_Job_Report_Photo__c.ozbee__Production_Job_Report__c,
        dailyReport.Id
      )
      .count(10)
      .create();
  }

  @isTest
  private static void getDailyReports() {
    List<ozbee__Production_Job_Report__c> dailyReports = [
      SELECT Id
      FROM ozbee__Production_Job_Report__c
    ];

    Test.startTest();
    Map<Id, ozbee__Production_Job_Report__c> dailyReportIdsToDailyReports = DailyReportService.getDailyReports(
      new List<Id>(Pluck.ids(dailyReports))
    );
    Test.stopTest();

    Integer actualDailyReportsReturned = dailyReportIdsToDailyReports.keySet()
      .size();
    Integer expectedDailyReportsReturned = 1;

    Assert.areEqual(
      expectedDailyReportsReturned,
      actualDailyReportsReturned,
      'Actual number of daily reports returned does not match the expected number'
    );

    Integer actualDailyReportPhotosReturned = dailyReportIdsToDailyReports.get(
        dailyReports[0].Id
      )
      .ozbee__Production_Job_Report_Photos__r.size();
    Integer expectedDailyReportPhotosReturned = 10;

    Assert.areEqual(
      actualDailyReportPhotosReturned,
      expectedDailyReportPhotosReturned,
      'Actual number of daily report photos returned does not match the expected number'
    );
  }

  @isTest
  private static void createDefaultChecklistItems() {
    List<ozbee__Production_Job_Report__c> dailyReports = new SObjectBuilder(
        ozbee__Production_Job_Report__c.sObjectType
      )
      .put(
        ozbee__Production_Job_Report__c.ozbee__Production_Job__c,
        [SELECT Id FROM ozbee__Production_Job__c LIMIT 1].Id
      )
      .put(
        ozbee__Production_Job_Report__c.Opportunity__c,
        [SELECT Id FROM Opportunity LIMIT 1].Id
      )
      .count(5)
      .create()
      .getRecords();

    ozbee__Production_Job_Checklist_Template__c checklistTemplate = (ozbee__Production_Job_Checklist_Template__c) new SObjectBuilder(
        ozbee__Production_Job_Checklist_Template__c.sObjectType
      )
      .put(ozbee__Production_Job_Checklist_Template__c.Active__c, true)
      .put(ozbee__Production_Job_Checklist_Template__c.Default__c, true)
      .count(5)
      .create()
      .getRecord();

    new SObjectBuilder(
        ozbee__Production_Job_Checklist_Template_Item__c.sObjectType
      )
      .put(
        ozbee__Production_Job_Checklist_Template_Item__c.ozbee__Production_Job_Checklist_Template__c,
        checklistTemplate.Id
      )
      .count(10)
      .create();

    Test.startTest();
    DailyReportService.createDefaultChecklistItems(dailyReports);
    Test.stopTest();

    Integer expectedNumberOfDailyReportChecklists = 250;
    Integer actualNumberOfDailyReportChecklists = [
      SELECT COUNT()
      FROM Daily_Report_Checklist__c
    ];

    Assert.areEqual(
      actualNumberOfDailyReportChecklists,
      actualNumberOfDailyReportChecklists,
      'Number of daily report checklist records returned does not match expected number.'
    );

    Integer expectedNumberOfDailyReportItems = 50;
    Integer actualNumberOfDailyReportItems = [
      SELECT COUNT()
      FROM ozbee__Production_Job_Report_Item__c
    ];

    Assert.areEqual(
      expectedNumberOfDailyReportItems,
      actualNumberOfDailyReportItems,
      'Number of daily report checklist records returned does not match expected number.'
    );
  }

  @isTest
  private static void createDailyExpectedProductions() {
    ozbee__Production_Job__c productionJob = [
      SELECT Id
      FROM ozbee__Production_Job__c
      LIMIT 1
    ];

    ozbee__Production_Schedule_Item__c productionScheduleItem = (ozbee__Production_Schedule_Item__c) new SObjectBuilder(
        ozbee__Production_Schedule_Item__c.sObjectType
      )
      .put(
        ozbee__Production_Schedule_Item__c.ozbee__Production_Job__c,
        productionJob.Id
      )
      .put(
        ozbee__Production_Schedule_Item__c.ozbee__Start_Date__c,
        Date.today()
      )
      .put(
        ozbee__Production_Schedule_Item__c.ozbee__End_Date__c,
        Date.today() + 1
      )
      .create()
      .getRecord();

    // new SObjectBuilder(ozbee__Production_Schedule_Item_Day__c.sObjectType)
    // 	.put(ozbee__Production_Schedule_Item_Day__c.ozbee__Production_Schedule_Item__c, productionScheduleItem.Id)
    // 	.put(ozbee__Production_Schedule_Item_Day__c.ozbee__Date__c, Date.today())
    // 	.count(10)
    // 	.create();

    List<ozbee__Production_Job_Report__c> dailyReports = [
      SELECT Id, ozbee__Production_Job__c
      FROM ozbee__Production_Job_Report__c
    ];

    Test.startTest();
    DailyReportService.createDailyExpectedProductions(dailyReports);
    Test.stopTest();

    Integer expectedDailyExpectedProduction = 1;
    Integer actualDailyExpectedProduction = [
      SELECT COUNT()
      FROM Daily_Expected_Production__c
    ];

    Assert.areEqual(
      expectedDailyExpectedProduction,
      actualDailyExpectedProduction,
      'Number of daily expected production records returned does not match expected number.'
    );
  }

  @isTest
  private static void addSafetyManagerToOpportunityTeam() {
    User user = (User) new SObjectBuilder(User.sObjectType)
      .create()
      .getRecord();

    List<ozbee__Production_Job_Report__c> dailyReports = [
      SELECT Id, ozbee__Safety_Manager__c, Opportunity__c
      FROM ozbee__Production_Job_Report__c
    ];
    Map<Id, ozbee__Production_Job_Report__c> oldDailyReportsMap = new Map<Id, ozbee__Production_Job_Report__c>(
      dailyReports
    );

    Assert.areEqual(
      1,
      dailyReports.size(),
      'Should have returned exactly 1 Daily Report record'
    );

    List<ozbee__Production_Job_Report__c> newDailyReports = new List<ozbee__Production_Job_Report__c>{
      dailyReports[0]
    };
    newDailyReports[0].ozbee__Safety_Manager__c = user.Id;

    Test.startTest();
    DailyReportService.addSafetyManagerToOpportunityTeam(
      newDailyReports,
      oldDailyReportsMap
    );
    Test.stopTest();

    OpportunityTeamMember opportunityTeamMember = [
      SELECT Id
      FROM OpportunityTeamMember
      WHERE UserId = :user.Id
    ];

    Assert.isNotNull(
      opportunityTeamMember,
      'User was not added as an opportunity team member'
    );
  }
}