force-app/main/default/objects/Daily_Expected_Production__c/Daily_Expected_Production__c.object-meta.xml
<CustomObject>
    <label>Daily Expected Production</label>
    <nameField>
        <displayFormat>DEP-{0000}</displayFormat>
        <label>Daily Expected Production Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Expected Productions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Expected_Production__c/fields/Completed__c.field-meta.xml
<CustomField>
    <fullName>Completed__c</fullName>
    <label>Completed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Daily_Expected_Production__c/fields/Daily_Report__c.field-meta.xml
<CustomField>
    <fullName>Daily_Report__c</fullName>
    <label>Daily Report</label>
    <referenceTo>ozbee__Production_Job_Report__c</referenceTo>
    <relationshipLabel>Daily Expected Productions</relationshipLabel>
    <relationshipName>Daily_Expected_Productions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Daily_Expected_Production__c/fields/Expected_Total__c.field-meta.xml
<CustomField>
    <fullName>Expected_Total__c</fullName>
    <label>Expected Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Daily_Expected_Production__c/fields/Measurement__c.field-meta.xml
<CustomField>
    <fullName>Measurement__c</fullName>
    <label>Measurement</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Expected_Production__c/fields/Previously_Completed__c.field-meta.xml
<CustomField>
    <fullName>Previously_Completed__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Previously Completed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Daily_Expected_Production__c/fields/Production_Schedule_Item__c.field-meta.xml
<CustomField>
    <fullName>Production_Schedule_Item__c</fullName>
    <label>Production Schedule Item</label>
    <referenceTo>ozbee__Production_Schedule_Item__c</referenceTo>
    <relationshipLabel>Daily Expected Productions</relationshipLabel>
    <relationshipName>Daily_Expected_Productions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ozbee__Production_Job__c/ozbee__Production_Job__c.object-meta.xml
<CustomObject>
    <label>Production Job</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Production Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Production Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ozbee__Production_Job_Checklist_Template__c/ozbee__Production_Job_Checklist_Template__c.object-meta.xml
<CustomObject>
    <label>Production Job Checklist Template</label>
    <nameField>
        <displayFormat>PJCT-{000000000}</displayFormat>
        <label>Production Job Checklist Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Production Job Checklist Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ozbee__Production_Job_Checklist_Template_Item__c/ozbee__Production_Job_Checklist_Template_Item__c.object-meta.xml
<CustomObject>
    <label>Production Job Checklist Template Item</label>
    <nameField>
        <displayFormat>PJCTI-{000000000}</displayFormat>
        <label>Production Job Checklist Template Items</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Production Job Checklist Template Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ozbee__Production_Job_Checklist_Template_Item__c/fields/ozbee__Production_Job_Checklist_Template__c.field-meta.xml
<CustomField>
    <fullName>ozbee__Production_Job_Checklist_Template__c</fullName>
    <label>Production Job Checklist Template</label>
    <referenceTo>ozbee__Production_Job_Checklist_Template__c</referenceTo>
    <relationshipLabel
  >Production Job Checklist Template Items</relationshipLabel>
    <relationshipName>Production_Job_Checklist_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ozbee__Production_Job_Report__c/ozbee__Production_Job_Report__c.object-meta.xml
<CustomObject>
    <label>Daily Report</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{DD}-{000000000}</displayFormat>
        <label>Daily Report Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ozbee__Production_Job_Report__c/fields/CompanyCam_Project_ID__c.field-meta.xml
<CustomField>
    <fullName>CompanyCam_Project_ID__c</fullName>
    <formula>Building__r.ozbee__CompanyCam_Project_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CompanyCam Project ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ozbee__Production_Job_Report__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Daily Reports</relationshipLabel>
    <relationshipName>Daily_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ozbee__Production_Schedule_Item__c/ozbee__Production_Schedule_Item__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >ozbee__Production_Schedule_Layout</compactLayoutAssignment>
    <label>Production Schedule Item</label>
    <nameField>
        <label>Task / Phase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Schedule Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ozbee__Production_Schedule_Item__c/fields/Completed__c.field-meta.xml
<CustomField>
    <fullName>Completed__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Completed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ozbee__Production_Schedule_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Budgeted Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DailyReportService.cls
public with sharing class DailyReportService {
  @AuraEnabled
  public static Map<Id, ozbee__Production_Job_Report__c> getDailyReports(
    List<Id> dailyReportIds
  ) {
    return new Map<Id, ozbee__Production_Job_Report__c>(
      [
        SELECT
          Id,
          CompanyCam_Project_ID__c,
          (
            SELECT
              Id,
              Company_Cam_Photo_Id__c,
              ozbee__Daily_Report_Item__c,
              ozbee__Production_Job_Report__c
            FROM ozbee__Production_Job_Report_Photos__r
          )
        FROM ozbee__Production_Job_Report__c
        WHERE Id = :dailyReportIds
      ]
    );
  }

  public static void createDefaultChecklistItems(
    List<ozbee__Production_Job_Report__c> dailyReports
  ) {
    List<ozbee__Production_Job_Checklist_Template__c> defaultChecklistTemplates = ChecklistTemplateService.getDefaultChecklistTemplates();

    List<ozbee__Production_Job_Checklist_Template_Item__c> checklistTemplateItems = new List<ozbee__Production_Job_Checklist_Template_Item__c>();
    for (
      ozbee__Production_Job_Checklist_Template__c checklistTemplate : defaultChecklistTemplates
    ) {
      for (
        ozbee__Production_Job_Checklist_Template_Item__c item : checklistTemplate.ozbee__Production_Job_Checklist_Items__r
      ) {
        checklistTemplateItems.add(item);
      }
    }

    DailyReportChecklistService.createDailyReportChecklists(
      Pluck.ids(dailyReports),
      Pluck.ids(defaultChecklistTemplates)
    );
    DailyReportItemService.createDailyReportItems(
      Pluck.ids(dailyReports),
      checklistTemplateItems
    );
  }

  public static void createDailyExpectedProductions(
    List<ozbee__Production_Job_Report__c> dailyReports
  ) {
    Map<Id, ozbee__Production_Job__c> productionScheduleItemsByJob = ProductionScheduleItemService.getProductionScheduleItemsByJob(
      Pluck.ids('ozbee__Production_Job__c', dailyReports)
    );

    List<Daily_Expected_Production__c> dailyExpectedProductionsToInsert = new List<Daily_Expected_Production__c>();

    for (ozbee__Production_Job_Report__c dailyReport : dailyReports) {
      List<ozbee__Production_Schedule_Item__c> productionScheduleItems = productionScheduleItemsByJob.get(
          dailyReport.ozbee__Production_Job__c
        )
        .ozbee__Production_Schedule_Items__r;

      if (
        productionScheduleItems == null ||
        productionScheduleItems.size() == 0
      ) {
        continue;
      }

      for (
        ozbee__Production_Schedule_Item__c productionScheduleItem : productionScheduleItems
      ) {
        dailyExpectedProductionsToInsert.add(
          new Daily_Expected_Production__c(
            Daily_Report__c = dailyReport.Id,
            Production_Schedule_Item__c = productionScheduleItem.Id,
            Date__c = Date.today(),
            Expected_Total__c = productionScheduleItem.Quantity__c,
            Previously_Completed__c = productionScheduleItem.Completed__c,
            Measurement__c = productionScheduleItem.Measurement__c
          )
        );
      }

      if (dailyExpectedProductionsToInsert.size() > 0) {
        insert dailyExpectedProductionsToInsert;
      }
    }
  }

  public static void addSafetyManagerToOpportunityTeam(
    List<ozbee__Production_Job_Report__c> newDailyReports,
    Map<Id, ozbee__Production_Job_Report__c> oldDailyReportsMap
  ) {
    List<ozbee__Production_Job_Report__c> filteredDailyReports = new List<ozbee__Production_Job_Report__c>();

    for (ozbee__Production_Job_Report__c dailyReport : newDailyReports) {
      if (
        oldDailyReportsMap.size() > 0 &&
        dailyReport.ozbee__Safety_Manager__c !=
        oldDailyReportsMap.get(dailyReport.Id).ozbee__Safety_Manager__c
      ) {
        filteredDailyReports.add(dailyReport);
      } else if (dailyReport.ozbee__Safety_Manager__c != null) {
        filteredDailyReports.add(dailyReport);
      }
    }

    Map<Id, Opportunity> opportunities = new Map<Id, Opportunity>(
      [
        SELECT
          Id,
          (SELECT Id, UserId, TeamMemberRole FROM OpportunityTeamMembers)
        FROM Opportunity
        WHERE Id IN :Pluck.ids('Opportunity__c', filteredDailyReports)
      ]
    );

    List<OpportunityTeamMember> opportunityTeamMembers = new List<OpportunityTeamMember>();

    for (ozbee__Production_Job_Report__c dailyReport : filteredDailyReports) {
      Opportunity opportunity = opportunities.get(dailyReport.Opportunity__c);

      Set<Id> teamMemberUserIds = Pluck.ids(
        'UserId',
        opportunity.OpportunityTeamMembers
      );

      if (!teamMemberUserIds.contains(dailyReport.ozbee__Safety_Manager__c)) {
        opportunityTeamMembers.add(
          new OpportunityTeamMember(
            OpportunityId = opportunity.Id,
            OpportunityAccessLevel = 'Edit',
            UserId = dailyReport.ozbee__Safety_Manager__c,
            TeamMemberRole = 'Safety Manager'
          )
        );
      }
    }

    if (opportunityTeamMembers.size() > 0) {
      insert opportunityTeamMembers;
    }
  }
}