force-app/main/default/objects/Daily_Expected_Production__c/Daily_Expected_Production__c.object-meta.xml
<CustomObject>
    <label>Daily Expected Production</label>
    <nameField>
        <displayFormat>DEP-{0000}</displayFormat>
        <label>Daily Expected Production Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Expected Productions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ozbee__Production_Job_Report__c/ozbee__Production_Job_Report__c.object-meta.xml
<CustomObject>
    <label>Daily Report</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{DD}-{000000000}</displayFormat>
        <label>Daily Report Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ozbee__Production_Job_Report__c/fields/CompanyCam_Project_ID__c.field-meta.xml
<CustomField>
    <fullName>CompanyCam_Project_ID__c</fullName>
    <formula>Building__r.ozbee__CompanyCam_Project_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CompanyCam Project ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ozbee__Production_Job_Report_Item__c/ozbee__Production_Job_Report_Item__c.object-meta.xml
<CustomObject>
    <label>Daily Report Item</label>
    <nameField>
        <label>Daily Report Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Daily Report Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ozbee__Production_Job_Report_Photo__c/ozbee__Production_Job_Report_Photo__c.object-meta.xml
<CustomObject>
    <label>Daily Report Photo</label>
    <nameField>
        <displayFormat>DRP-{000000000}</displayFormat>
        <label>Daily Report Photo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Report Photos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/UpdateDailyReportController.cls
public with sharing class UpdateDailyReportController {
  @AuraEnabled
  public static void updateDailyReportItems(
    String dailyReportItemsString,
    String dailyReportPhotosString
  ) {
    try {
      List<ozbee__Production_Job_Report_Item__c> dailyReportItems = (List<ozbee__Production_Job_Report_Item__c>) JSON.deserialize(
        dailyReportItemsString,
        List<ozbee__Production_Job_Report_Item__c>.class
      );

      List<ozbee__Production_Job_Report_Photo__c> dailyReportItemPhotos = (List<ozbee__Production_Job_Report_Photo__c>) JSON.deserialize(
        dailyReportPhotosString,
        List<ozbee__Production_Job_Report_Photo__c>.class
      );

      update dailyReportItems;

      DailyReportPhotoService.deleteDailyReportPhotos(
        new Set<Id>{ dailyReportItems[0].ozbee__Production_Job_Report__c }
      );
      insert dailyReportItemPhotos;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  @AuraEnabled
  public static void updateDailyExpectedProductions(
    String dailyExpectedProductionsString
  ) {
    try {
      List<Daily_Expected_Production__c> dailyExpectedProductions = (List<Daily_Expected_Production__c>) JSON.deserialize(
        dailyExpectedProductionsString,
        List<Daily_Expected_Production__c>.class
      );

      update dailyExpectedProductions;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  @AuraEnabled
  public static List<CompanyCamPhoto> getProjectPhotos(String companyCamId) {
    try {
      return CompanyCamCalloutUtility.loadCompanyCamPhotos(companyCamId);
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  @AuraEnabled
  public static DailyReportData getDailyReportData(Id dailyReportId) {
    ozbee__Production_Job_Report__c dailyReport = DailyReportService.getDailyReports(
        new List<Id>{ dailyReportId }
      )
      .get(dailyReportId);

    return new DailyReportData(
      dailyReport,
      DailyReportItemService.getDailyReportItems(dailyReportId),
      DailyExpectedProductionService.getDailyReportExpectedProduction(
        dailyReportId
      ),
      CompanyCamCalloutUtility.loadCompanyCamPhotos(
        dailyReport.CompanyCam_Project_ID__c
      )
    );
  }

  public class DailyReportData {
    @AuraEnabled
    public ozbee__Production_Job_Report__c dailyReport { get; set; }
    @AuraEnabled
    public List<ozbee__Production_Job_Report_Item__c> dailyReportItems {
      get;
      set;
    }
    @AuraEnabled
    public List<Daily_Expected_Production__c> dailyExpectedProduction {
      get;
      set;
    }
    @AuraEnabled
    public List<CompanyCamPhoto> projectPhotos { get; set; }

    public DailyReportData(
      ozbee__Production_Job_Report__c dailyReport,
      List<ozbee__Production_Job_Report_Item__c> dailyReportItems,
      List<Daily_Expected_Production__c> dailyExpectedProduction,
      List<CompanyCamPhoto> projectPhotos
    ) {
      this.dailyReport = dailyReport;
      this.dailyReportItems = dailyReportItems;
      this.dailyExpectedProduction = dailyExpectedProduction;
      this.projectPhotos = projectPhotos;
    }
  }
}