force-app/main/default/objects/Daily_Report_Checklist__c/Daily_Report_Checklist__c.object-meta.xml
<CustomObject>
    <label>Daily Report Checklist</label>
    <nameField>
        <displayFormat>DRC-{000000000}</displayFormat>
        <label>Daily Report Checklists</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Report Checklists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Report_Checklist__c/fields/Daily_Report__c.field-meta.xml
<CustomField>
    <fullName>Daily_Report__c</fullName>
    <label>Daily Report</label>
    <referenceTo>ozbee__Production_Job_Report__c</referenceTo>
    <relationshipLabel>Daily Report Checklists</relationshipLabel>
    <relationshipName>Daily_Report_Checklists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Daily_Report_Checklist__c/fields/Production_Job_Checklist_Template__c.field-meta.xml
<CustomField>
    <fullName>Production_Job_Checklist_Template__c</fullName>
    <label>Production Job Checklist Template</label>
    <referenceTo>ozbee__Production_Job_Checklist_Template__c</referenceTo>
    <relationshipLabel>Daily Report Checklists</relationshipLabel>
    <relationshipName>Daily_Report_Checklists</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ozbee__Production_Job_Checklist_Template__c/ozbee__Production_Job_Checklist_Template__c.object-meta.xml
<CustomObject>
    <label>Production Job Checklist Template</label>
    <nameField>
        <displayFormat>PJCT-{000000000}</displayFormat>
        <label>Production Job Checklist Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Production Job Checklist Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ozbee__Production_Job_Checklist_Template_Item__c/ozbee__Production_Job_Checklist_Template_Item__c.object-meta.xml
<CustomObject>
    <label>Production Job Checklist Template Item</label>
    <nameField>
        <displayFormat>PJCTI-{000000000}</displayFormat>
        <label>Production Job Checklist Template Items</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Production Job Checklist Template Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ozbee__Production_Job_Checklist_Template_Item__c/fields/ozbee__Production_Job_Checklist_Template__c.field-meta.xml
<CustomField>
    <fullName>ozbee__Production_Job_Checklist_Template__c</fullName>
    <label>Production Job Checklist Template</label>
    <referenceTo>ozbee__Production_Job_Checklist_Template__c</referenceTo>
    <relationshipLabel
  >Production Job Checklist Template Items</relationshipLabel>
    <relationshipName>Production_Job_Checklist_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ozbee__Production_Job_Checklist_Template_Item__c/fields/ozbee__Task_Name__c.field-meta.xml
<CustomField>
    <fullName>ozbee__Task_Name__c</fullName>
    <label>Task Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ChecklistTemplateService.cls
public with sharing class ChecklistTemplateService {
  public static List<ozbee__Production_Job_Checklist_Template__c> getUnusedChecklistTemplates(
    Id dailyReportId
  ) {
    return [
      SELECT Id, ozbee__Checklist_Type__c
      FROM ozbee__Production_Job_Checklist_Template__c
      WHERE
        Id NOT IN (
          SELECT Production_Job_Checklist_Template__c
          FROM Daily_Report_Checklist__c
          WHERE Daily_Report__c = :dailyReportId
        )
        AND Active__c = TRUE
    ];
  }

  public static List<ozbee__Production_Job_Checklist_Template__c> getActiveChecklistTemplates() {
    return [
      SELECT Id, ozbee__Checklist_Type__c
      FROM ozbee__Production_Job_Checklist_Template__c
      WHERE Active__c = TRUE
    ];
  }

  public static List<ozbee__Production_Job_Checklist_Template__c> getDefaultChecklistTemplates() {
    return [
      SELECT
        Id,
        ozbee__Checklist_Type__c,
        (
          SELECT
            Id,
            Name,
            ozbee__Task_Name__c,
            ozbee__Production_Job_Checklist_Template__r.ozbee__Checklist_Type__c,
            Order__c
          FROM ozbee__Production_Job_Checklist_Items__r
        )
      FROM ozbee__Production_Job_Checklist_Template__c
      WHERE Default__c = TRUE AND Active__c = TRUE
    ];
  }
}