force-app/main/default/objects/Daily_Report_Checklist__c/Daily_Report_Checklist__c.object-meta.xml
<CustomObject>
    <label>Daily Report Checklist</label>
    <nameField>
        <displayFormat>DRC-{000000000}</displayFormat>
        <label>Daily Report Checklists</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Report Checklists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Report_Checklist__c/fields/Daily_Report__c.field-meta.xml
<CustomField>
    <fullName>Daily_Report__c</fullName>
    <label>Daily Report</label>
    <referenceTo>ozbee__Production_Job_Report__c</referenceTo>
    <relationshipLabel>Daily Report Checklists</relationshipLabel>
    <relationshipName>Daily_Report_Checklists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Daily_Report_Checklist__c/fields/Production_Job_Checklist_Template__c.field-meta.xml
<CustomField>
    <fullName>Production_Job_Checklist_Template__c</fullName>
    <label>Production Job Checklist Template</label>
    <referenceTo>ozbee__Production_Job_Checklist_Template__c</referenceTo>
    <relationshipLabel>Daily Report Checklists</relationshipLabel>
    <relationshipName>Daily_Report_Checklists</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DailyReportChecklistService.cls
public with sharing class DailyReportChecklistService {
  public static void createDailyReportChecklists(
    Set<Id> dailyReportIds,
    Set<Id> checklistTemplateIds
  ) {
    List<Daily_Report_Checklist__c> dailyReportChecklists = new List<Daily_Report_Checklist__c>();

    for (Id dailyReportId : dailyReportIds) {
      for (Id checklistTemplateId : checklistTemplateIds) {
        dailyReportChecklists.add(
          new Daily_Report_Checklist__c(
            Daily_Report__c = dailyReportId,
            Production_Job_Checklist_Template__c = checklistTemplateId
          )
        );
      }
    }

    insert dailyReportChecklists;
  }
}