force-app/main/default/objects/ozbee__Production_Job_Checklist_Template__c/ozbee__Production_Job_Checklist_Template__c.object-meta.xml
<CustomObject>
    <label>Production Job Checklist Template</label>
    <nameField>
        <displayFormat>PJCT-{000000000}</displayFormat>
        <label>Production Job Checklist Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Production Job Checklist Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ozbee__Production_Job_Checklist_Template_Item__c/ozbee__Production_Job_Checklist_Template_Item__c.object-meta.xml
<CustomObject>
    <label>Production Job Checklist Template Item</label>
    <nameField>
        <displayFormat>PJCTI-{000000000}</displayFormat>
        <label>Production Job Checklist Template Items</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Production Job Checklist Template Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ozbee__Production_Job_Checklist_Template_Item__c/fields/ozbee__Production_Job_Checklist_Template__c.field-meta.xml
<CustomField>
    <fullName>ozbee__Production_Job_Checklist_Template__c</fullName>
    <label>Production Job Checklist Template</label>
    <referenceTo>ozbee__Production_Job_Checklist_Template__c</referenceTo>
    <relationshipLabel
  >Production Job Checklist Template Items</relationshipLabel>
    <relationshipName>Production_Job_Checklist_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DailyReportSelectChecklistsController.cls
public with sharing class DailyReportSelectChecklistsController {
  @AuraEnabled(cacheable=true)
  public static List<ozbee__Production_Job_Checklist_Template__c> getChecklistTemplates(
    Id dailyReportId
  ) {
    try {
      return ChecklistTemplateService.getUnusedChecklistTemplates(
        dailyReportId
      );
      // return ChecklistTemplateService.getActiveChecklistTemplates();
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  @AuraEnabled
  public static void createDailyReportItems(
    Id dailyReportId,
    String checklistTemplateIdsString
  ) {
    try {
      List<Id> checklistTemplateIds = (List<Id>) JSON.deserialize(
        checklistTemplateIdsString,
        List<Id>.class
      );

      DailyReportChecklistService.createDailyReportChecklists(
        new Set<Id>{ dailyReportId },
        new Set<Id>(checklistTemplateIds)
      );

      List<ozbee__Production_Job_Checklist_Template_Item__c> checklistTemplateItems = ChecklistTemplateItemsService.getChecklistTemplateItems(
        checklistTemplateIds
      );
      DailyReportItemService.createDailyReportItems(
        new Set<Id>{ dailyReportId },
        checklistTemplateItems
      );
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }
}