force-app/main/default/objects/ozbee__Production_Job_Checklist_Template__c/ozbee__Production_Job_Checklist_Template__c.object-meta.xml
<CustomObject>
    <label>Production Job Checklist Template</label>
    <nameField>
        <displayFormat>PJCT-{000000000}</displayFormat>
        <label>Production Job Checklist Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Production Job Checklist Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ozbee__Production_Job_Checklist_Template_Item__c/ozbee__Production_Job_Checklist_Template_Item__c.object-meta.xml
<CustomObject>
    <label>Production Job Checklist Template Item</label>
    <nameField>
        <displayFormat>PJCTI-{000000000}</displayFormat>
        <label>Production Job Checklist Template Items</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Production Job Checklist Template Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ozbee__Production_Job_Checklist_Template_Item__c/fields/ozbee__Production_Job_Checklist_Template__c.field-meta.xml
<CustomField>
    <fullName>ozbee__Production_Job_Checklist_Template__c</fullName>
    <label>Production Job Checklist Template</label>
    <referenceTo>ozbee__Production_Job_Checklist_Template__c</referenceTo>
    <relationshipLabel
  >Production Job Checklist Template Items</relationshipLabel>
    <relationshipName>Production_Job_Checklist_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ozbee__Production_Job_Checklist_Template_Item__c/fields/ozbee__Safety_Inspection_Category__c.field-meta.xml
<CustomField>
    <fullName>ozbee__Safety_Inspection_Category__c</fullName>
    <label>Inspection Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName
    >ozbee__Safety_Inspection_Checklist_Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ozbee__Production_Job_Checklist_Template_Item__c/fields/ozbee__Task_Name__c.field-meta.xml
<CustomField>
    <fullName>ozbee__Task_Name__c</fullName>
    <label>Task Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ChecklistTemplateItemsService.cls
public with sharing class ChecklistTemplateItemsService {
  public static List<ozbee__Production_Job_Checklist_Template_Item__c> getChecklistTemplateItems(
    List<Id> checklistTemplateIds
  ) {
    return [
      SELECT
        Id,
        Name,
        ozbee__Task_Name__c,
        ozbee__Safety_Inspection_Category__c,
        Order__c,
        ozbee__Production_Job_Checklist_Template__r.ozbee__Checklist_Type__c
      FROM ozbee__Production_Job_Checklist_Template_Item__c
      WHERE ozbee__Production_Job_Checklist_Template__c IN :checklistTemplateIds
      ORDER BY Order__c ASC
    ];
  }
}