force-app/main/default/objects/ozbee__Production_Job_Checklist_Template__c/ozbee__Production_Job_Checklist_Template__c.object-meta.xml
<CustomObject>
    <label>Production Job Checklist Template</label>
    <nameField>
        <displayFormat>PJCT-{000000000}</displayFormat>
        <label>Production Job Checklist Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Production Job Checklist Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ozbee__Production_Job_Checklist_Template_Item__c/ozbee__Production_Job_Checklist_Template_Item__c.object-meta.xml
<CustomObject>
    <label>Production Job Checklist Template Item</label>
    <nameField>
        <displayFormat>PJCTI-{000000000}</displayFormat>
        <label>Production Job Checklist Template Items</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Production Job Checklist Template Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ozbee__Production_Job_Checklist_Template_Item__c/fields/ozbee__Production_Job_Checklist_Template__c.field-meta.xml
<CustomField>
    <fullName>ozbee__Production_Job_Checklist_Template__c</fullName>
    <label>Production Job Checklist Template</label>
    <referenceTo>ozbee__Production_Job_Checklist_Template__c</referenceTo>
    <relationshipLabel
  >Production Job Checklist Template Items</relationshipLabel>
    <relationshipName>Production_Job_Checklist_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ChecklistTemplateItemsServiceTest.cls
@isTest
private with sharing class ChecklistTemplateItemsServiceTest {
  // # TEST PURPOSE: ensure the expected number of production job checklist template items are returned
  @isTest
  private static void getChecklistTemplateItemsTest() {
    // Query for parent Production Job Checklist Templates
    List<ozbee__Production_Job_Checklist_Template__c> productionJobChecklistTemplates = [
      SELECT Id
      FROM ozbee__Production_Job_Checklist_Template__c
    ];

    // Gather parent production job checklist template item Ids
    Set<Id> productionJobChecklistTemplateSetIds = Pluck.ids(
      productionJobChecklistTemplates
    );

    // Convert from a set to a list
    List<Id> productionJobChecklistTemplateListIds = new List<Id>();
    productionJobChecklistTemplateListIds.addAll(
      productionJobChecklistTemplateSetIds
    );

    Test.startTest();
    // Call the getChecklistTemplateItems method and store the results for assertion
    List<ozbee__Production_Job_Checklist_Template_Item__c> productionJobTemplateChecklistItems = ChecklistTemplateItemsService.getChecklistTemplateItems(
      productionJobChecklistTemplateListIds
    );
    Test.stopTest();

    // Store expected and actual values for readability and comparison
    Integer expectedNumberOfItemsReturned = 200;
    Integer actualNumberOfItemsReturned = productionJobTemplateChecklistItems.size();

    // ASSERTION
    Assert.areEqual(
      expectedNumberOfItemsReturned,
      actualNumberOfItemsReturned,
      'Number of Production Job Checklist Template Items returned does not match expected number.'
    );
  }

  @TestSetup
  static void makeData() {
    // Insert Production Job Checklist Template Items with parent Production Job Checklist Templates
    new SObjectBuilder(
        ozbee__Production_Job_Checklist_Template_Item__c.sObjectType
      )
      .count(200)
      .create();
  }
}