force-app/main/default/objects/ozbee__Production_Job_Checklist_Template__c/ozbee__Production_Job_Checklist_Template__c.object-meta.xml
<CustomObject>
    <label>Production Job Checklist Template</label>
    <nameField>
        <displayFormat>PJCT-{000000000}</displayFormat>
        <label>Production Job Checklist Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Production Job Checklist Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ozbee__Production_Job_Checklist_Template_Item__c/ozbee__Production_Job_Checklist_Template_Item__c.object-meta.xml
<CustomObject>
    <label>Production Job Checklist Template Item</label>
    <nameField>
        <displayFormat>PJCTI-{000000000}</displayFormat>
        <label>Production Job Checklist Template Items</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Production Job Checklist Template Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ozbee__Production_Job_Checklist_Template_Item__c/fields/ozbee__Production_Job_Checklist_Template__c.field-meta.xml
<CustomField>
    <fullName>ozbee__Production_Job_Checklist_Template__c</fullName>
    <label>Production Job Checklist Template</label>
    <referenceTo>ozbee__Production_Job_Checklist_Template__c</referenceTo>
    <relationshipLabel
  >Production Job Checklist Template Items</relationshipLabel>
    <relationshipName>Production_Job_Checklist_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ozbee__Production_Job_Report__c/ozbee__Production_Job_Report__c.object-meta.xml
<CustomObject>
    <label>Daily Report</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{DD}-{000000000}</displayFormat>
        <label>Daily Report Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ozbee__Production_Job_Report_Item__c/ozbee__Production_Job_Report_Item__c.object-meta.xml
<CustomObject>
    <label>Daily Report Item</label>
    <nameField>
        <label>Daily Report Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Daily Report Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/DailyReportSelectChecklistControllerTest.cls
@IsTest
private with sharing class DailyReportSelectChecklistControllerTest {
  // * TEST PURPOSE:
  @isTest
  private static void getChecklistTemplates() {
    // Create Production Job Checklist Templates with Default__c = false
    new SObjectBuilder(ozbee__Production_Job_Checklist_Template__c.sObjectType)
      .put(ozbee__Production_Job_Checklist_Template__c.Active__c, true)
      .put(
        ozbee__Production_Job_Checklist_Template__c.ozbee__Checklist_Type__c,
        SObjectFactory.provideUniqueString('NonDefault')
      )
      .count(2)
      .create();

    // Create a Daily Report to check against
    ozbee__Production_Job_Report__c dailyReport = (ozbee__Production_Job_Report__c) new SObjectBuilder(
        ozbee__Production_Job_Report__c.sObjectType
      )
      .create()
      .getRecord();

    Test.startTest();
    // Call the getUnusedChecklistTemplates() method
    List<ozbee__Production_Job_Checklist_Template__c> unusedChecklistTemplates = DailyReportSelectChecklistsController.getChecklistTemplates(
      dailyReport.Id
    );
    Test.stopTest();

    // Store expected and actual values for readability and comparison
    Integer expectedNumberOfItemsReturned = 2;
    Integer actualNumberOfItemsReturned = unusedChecklistTemplates.size();

    // ASSERTION
    Assert.areEqual(
      expectedNumberOfItemsReturned,
      actualNumberOfItemsReturned,
      'Number of Production Job Checklist Template Item records returned does not match expected number.'
    );
  }
  // * TEST PURPOSE:
  @isTest
  private static void createDailyReportItems() {
    // Create a single Daily Report record
    ozbee__Production_Job_Report__c dailyReport = (ozbee__Production_Job_Report__c) new SObjectBuilder(
        ozbee__Production_Job_Report__c.sObjectType
      )
      .create()
      .getRecord();
    // Create a single Production Job Checklist Template record
    List<ozbee__Production_Job_Checklist_Template_Item__c> checklistTemplateItems = new SObjectBuilder(
        ozbee__Production_Job_Checklist_Template_Item__c.sObjectType
      )
      .count(50)
      .create()
      .getRecords();

    Set<Id> checklistTemplateSetIds = Pluck.ids(
      'ozbee__Production_Job_Checklist_Template__c',
      checklistTemplateItems
    );

    String checklistTemplateIdsString = JSON.serialize(checklistTemplateSetIds);

    Test.startTest();
    // Call the getDailyReportExpectedProduction() method
    DailyReportSelectChecklistsController.createDailyReportItems(
      dailyReport.Id,
      checklistTemplateIdsString
    );
    Test.stopTest();

    // Query for Daily Report Checklist records that should have been inserted into the database
    List<ozbee__Production_Job_Report_Item__c> dailyReportItems = [
      SELECT Id
      FROM ozbee__Production_Job_Report_Item__c
    ];

    // Store expected and actual values for readability and comparison
    Integer expectedNumberOfItemsCreated = 50;
    Integer actualNumberOfItemsCreated = dailyReportItems.size();

    // ASSERTION
    Assert.areEqual(
      expectedNumberOfItemsCreated,
      actualNumberOfItemsCreated,
      'Number of created Daily Report Item records returned does not match expected number.'
    );
  }
  // * TEST PURPOSE:
  @isTest
  private static void createDailyReportItemsError() {
    // Create a single Daily Report record
    ozbee__Production_Job_Report__c dailyReport = (ozbee__Production_Job_Report__c) new SObjectBuilder(
        ozbee__Production_Job_Report__c.sObjectType
      )
      .create()
      .getRecord();

    String checklistTemplateIdsString = JSON.serialize(
      'forceError, asdfawefwef'
    );
    try {
      Test.startTest();
      // Call the getDailyReportExpectedProduction() method
      DailyReportSelectChecklistsController.createDailyReportItems(
        dailyReport.Id,
        checklistTemplateIdsString
      );
      Test.stopTest();
    } catch (Exception e) {
      Boolean containsExpectedException = e.getMessage()
        .contains('Script-thrown');
      Assert.areEqual(
        true,
        containsExpectedException,
        'The expected exception was not thrown.'
      );
    }
  }
}